package v1

// This file contains methods that can be used by the go-restful package to generate Swagger
// documentation for the object types found in 'types.go' This file is automatically generated
// by hack/update-generated-swagger-descriptions.sh and should be run after a full build of OpenShift.
// ==== DO NOT EDIT THIS FILE MANUALLY ====

var map_Site = map[string]string{
	"":         "Site information in Ubernetes",
	"metadata": "Standard object's metadata. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#metadata",
	"spec":     "Spec defines the behavior of the Site.",
	"status":   "Status describes the current status of a Site",
}

func (Site) SwaggerDoc() map[string]string {
	return map_Site
}

var map_SiteAddress = map[string]string{
	"":    "Address of a site",
	"url": "URL to access the site",
}

func (SiteAddress) SwaggerDoc() map[string]string {
	return map_SiteAddress
}

var map_SiteList = map[string]string{
	"":         "A list of Sites",
	"metadata": "Standard list metadata. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds",
	"items":    "List of Site objects.",
}

func (SiteList) SwaggerDoc() map[string]string {
	return map_SiteList
}

var map_SiteMeta = map[string]string{
	"":        "Site metadata",
	"version": "Version of the site",
}

func (SiteMeta) SwaggerDoc() map[string]string {
	return map_SiteMeta
}

var map_SiteSpec = map[string]string{
	"":           "SiteSpec describes the attributes on a Site.",
	"type":       "Type of the site",
	"address":    "Address of the site",
	"credential": "The credential used to access site. It’s used for system routines (not behalf of users)",
	"Finalizers": "Finalizers is an opaque list of values that must be empty to permanently remove object from storage",
}

func (SiteSpec) SwaggerDoc() map[string]string {
	return map_SiteSpec
}

var map_SiteStatus = map[string]string{
	"":                 "SiteStatus is information about the current status of a site.",
	"phase":            "Phase is the recently observed lifecycle phase of the site.",
	"siteAgentAddress": "SiteAgentAddress is the address of the site agent.",
}

func (SiteStatus) SwaggerDoc() map[string]string {
	return map_SiteStatus
}

var map_StringSource = map[string]string{
	"":                 "StringSource allows specifying a string inline, or externally via env var or file. When it contains only a string value, it marshals to a simple JSON string.",
	"StringSourceSpec": "StringSourceSpec specifies the string value, or external location",
}

func (StringSource) SwaggerDoc() map[string]string {
	return map_StringSource
}

var map_StringSourceSpec = map[string]string{
	"":        "StringSourceSpec specifies a string value, or external location",
	"Value":   "Value specifies the cleartext value, or an encrypted value if keyFile is specified.",
	"Env":     "Env specifies an envvar containing the cleartext value, or an encrypted value if the keyFile is specified.",
	"File":    "File references a file containing the cleartext value, or an encrypted value if a keyFile is specified.",
	"KeyFile": "KeyFile references a file containing the key to use to decrypt the value.",
}

func (StringSourceSpec) SwaggerDoc() map[string]string {
	return map_StringSourceSpec
}
